name: "Reportar bug"
title: "[BUG] "
labels: [bug]

body:
  - type: input
    id: version
    attributes:
      label: "Versão"
      placeholder: "Ex: v1.2.3"
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: "Plataforma"
      options:
        - Linux
        - Windows
        - macOS
        - Outro

  - type: textarea
    id: steps
    attributes:
      label: "Passos para reproduzir"
      description: "Descreva os passos para reproduzir o bug"

  - type: textarea
    id: frequency
    attributes:
      label: "Frequência"
      description: "Descreva a frequência que acontece o bug"

  - type: textarea
    id: expected
    attributes:
      label: "Comportamento esperado"
      placeholder: "O que deveria acontecer?"

  - type: textarea
    id: actual
    attributes:
      label: "Comportamento atual"
      placeholder: "O que realmente acontece?"

  - type: textarea
    id: extra
    attributes:
      label: "Informações adicionais"
      description: "Logs, prints, ou contexto extra."
