# Generated by Django 5.1.6 on 2025-02-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='resource_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='resource_type',
            field=models.CharField(choices=[('auditorium', 'Auditório'), ('meeting_room', 'Sala de Reunião'), ('vehicle', 'Veículo')], max_length=20, null=True),
        ),
    ]
