# Generated by Django 5.1.6 on 2025-10-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0003_reservation_resource_id_reservation_resource_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_anonymized',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(blank=True, choices=[('Pendente', 'Pending'), ('Aprovado', 'Approved'), ('Reprovado', 'Rejected'), ('Bloqueado', 'Blocked')], default='Pendente', max_length=10),
        ),
    ]
