# Generated by Django 5.2.6 on 2025-10-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0004_add_lgpd_consent_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(blank=True, choices=[('Pendente', 'Pending'), ('Aprovado', 'Approved'), ('Reprovado', 'Rejected'), ('Bloqueado', 'Blocked')], default='Pendente', max_length=10),
        ),
    ]
